### ISSUE TITLE
Loosen restrictions on number of steps for Pixel-Flipping

### ISSUE THREAD

**Issue by rodrigobdz** [understandable-machine-intelligence-lab/Quantus#104]
Pixel-Flipping has a check called `assert_max_steps` related to the maximum number of steps passed as an argument in `max_steps_per_input`. This check seems too restrictive and I am not sure about its exact purpose or meaning; perhaps it's actually meant for Region Perturbation.

Instead, a natural check for the `max_steps_per_input` parameter would be an **upper bound limit** regarding  the **total number of pixels** in the input to avoid flipping the same pixels more than once.

https://github.com/understandable-machine-intelligence-lab/Quantus/blob/1ecb500195f985f7b7a6a7086cba82219d76c6c6/quantus/metrics/faithfulness_metrics.py#L1369-L1372

https://github.com/understandable-machine-intelligence-lab/Quantus/blob/1ecb500195f985f7b7a6a7086cba82219d76c6c6/quantus/helpers/asserts.py#L76-L81

**Comment by annahedstroem** [comment]
Hmm, I think there is confusion here with what is the intended purpose of `max_steps_per_input`.

I originally implemented it as an alternative to specifying `features_in_step` to allow the user to automatically infer the number of `features_in_step` by splitting the input size by the maximum steps per input. I see that it is not well-documented in the library, so to avoid future confusion, I will remove this in future releases of the library.

**Comment by annahedstroem** [comment]
Fixed in PR: https://github.com/understandable-machine-intelligence-lab/Quantus/pull/114
