### ISSUE TITLE
taking absolute before normalisation makes normalise_by_negative defective

### ISSUE THREAD

**Issue by dkrako** [understandable-machine-intelligence-lab/Quantus#110]
I'm not sure if this is intended, but all metrics first take the absolute of the attributions, then apply normalisation.

But if we want to normalise the positive and the negative sides differently like it's done in `normalise_by_negative` it would be more reasonable to normalise first, and then take the absolute.

Am I missing something, or is this a bug?

**Comment by annahedstroem** [comment]
Agree, had planned to fix this before. It will be fixed in upcoming commits @dkrako

**Comment by annahedstroem** [comment]
Fixed in PR: https://github.com/understandable-machine-intelligence-lab/Quantus/pull/114
