### ISSUE TITLE
Tutorial notebook TypeError: Callable() takes no arguments

### ISSUE THREAD

**Issue by ofirmoshe** [understandable-machine-intelligence-lab/Quantus#123]
Hi!
I'm trying to run the [tutorial_model_training_explanation_robustness.ipynb](https://github.com/understandable-machine-intelligence-lab/Quantus/blob/main/tutorials/tutorial_model_training_explanation_robustness.ipynb) notebook and I get the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-7-432ed12102bf>](https://localhost:8080/#) in <module>()
     50                                                                         y_batch=y_batch.cpu().numpy(),
     51                                                                         a_batch=None,
---> 52                                                                         **{"method": "Saliency", "device": device, "img_size": 28}) 
     53 
     54     print(f"Epoch {epoch+1}/{epochs} - loss {loss.item():.2f} - test accuracy: {(100 * test_acc):.2f}% - max sensitivity {np.mean(sensitivities[epoch]):.2f}")

1 frames
[/usr/local/lib/python3.7/dist-packages/quantus/metrics/robustness_metrics.py](https://localhost:8080/#) in __call__(self, model, x_batch, y_batch, a_batch, *args, **kwargs)
    432                 inputs=x_batch,
    433                 targets=y_batch,
--> 434                 **self.kwargs,
    435             )
    436 

[/usr/lib/python3.7/typing.py](https://localhost:8080/#) in __call__(self, *args, **kwargs)
    676             raise TypeError(f"Type {self._name} cannot be instantiated; "
    677                             f"use {self._name.lower()}() instead")
--> 678         result = self.__origin__(*args, **kwargs)
    679         try:
    680             result.__orig_class__ = self

TypeError: Callable() takes no arguments
```

**Comment by annahedstroem** [comment]
Are you passing/ specifuing an `explain_func`?

**Comment by ofirmoshe** [comment]
> Are you passing/ specifying an `explain_func`?

I did not change the code at all. It passes quantus.explain, is it defaults to something or I need to specify it? 
My goal is evaluating the robustness of a model to input perturbations, which explain func should I specify for it?

**Comment by ofirmoshe** [comment]
> Are you passing/ specifying an `explain_func`?

It seems like there was a problem with the 'kwargs', something went wrong with passing it from the constructor to the call().
I managed to get through it by passing the arguments to the __call__ too.
Now I encounter another issue when running it - can you help me with it please? Thanks!


`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [10], in <cell line: 1>()
----> 1 sensitivities = quantus.MaxSensitivity(explain_func=quantus.explain,
      2                                                                         method="Saliency",
      3                                                                         nr_samples=10, perturb_radius=0.2, norm_numerator=quantus.fro_norm, norm_denominator=quantus.fro_norm, perturb_func=quantus.uniform_noise, similarity_func=quantus.difference, device=device, img_size=32)(model=model_vanilla,
      4                                                                         x_batch=X_test.cpu().numpy(),
      5                                                                         y_batch=y_test.cpu().numpy(),
      6                                                                         a_batch=None, explain_func=quantus.explain,
      7                                                                         method="Saliency",
      8                                                                         nr_samples=10, perturb_radius=0.2, norm_numerator=quantus.fro_norm, norm_denominator=quantus.fro_norm, perturb_func=quantus.uniform_noise, similarity_func=quantus.difference, device=device, img_size=32)

File ~/.conda/envs/ofir_env/lib/python3.8/site-packages/quantus/metrics/robustness_metrics.py:473, in MaxSensitivity.__call__(self, model, x_batch, y_batch, a_batch, *args, **kwargs)
    470 asserts.assert_perturbation_caused_change(x=x, x_perturbed=x_perturbed)
    472 # Generate explanation based on perturbed input x.
--> 473 a_perturbed = explain_func(
    474     model=model.get_model(),
    475     inputs=x_input,
    476     targets=y,
    477     **self.kwargs,
    478 )
    480 if self.normalise:
    481     a_perturbed = self.normalise_func(a_perturbed)

File ~/.conda/envs/ofir_env/lib/python3.8/site-packages/quantus/helpers/explanation_func.py:64, in explain(model, inputs, targets, **kwargs)
     58 if not __EXTRAS__:
     59     raise ImportError(
     60         "Explanation library not found. Please install Captum or Zennit for torch>=1.2 models "
     61         "and tf-explain for TensorFlow>=2.0."
     62     )
---> 64 explanation = get_explanation(model, inputs, targets, **kwargs)
     66 return explanation

File ~/.conda/envs/ofir_env/lib/python3.8/site-packages/quantus/helpers/explanation_func.py:84, in get_explanation(model, inputs, targets, **kwargs)
     82         return generate_zennit_explanation(model, inputs, targets, **kwargs)
     83 if util.find_spec("captum"):
---> 84     return generate_captum_explanation(model, inputs, targets, **kwargs)
     85 if util.find_spec("zennit"):
     86     return generate_zennit_explanation(model, inputs, targets, **kwargs)

File ~/.conda/envs/ofir_env/lib/python3.8/site-packages/quantus/helpers/explanation_func.py:292, in generate_captum_explanation(model, inputs, targets, device, **kwargs)
    284     explanation = (
    285         InputXGradient(model)
    286         .attribute(inputs=inputs, target=targets)
    287         .sum(**reduce_axes)
    288     )
    290 elif method == "Saliency".lower():
    291     explanation = (
--> 292         Saliency(model)
    293         .attribute(inputs=inputs, target=targets, abs=True)
    294         .sum(**reduce_axes)
    295     )
    297 elif method == "Gradient".lower():
    298     explanation = (
    299         Saliency(model)
    300         .attribute(inputs=inputs, target=targets, abs=False)
    301         .sum(**reduce_axes)
    302     )

File ~/.conda/envs/ofir_env/lib/python3.8/site-packages/captum/log/__init__.py:35, in log_usage.<locals>._log_usage.<locals>.wrapper(*args, **kwargs)
     33 @wraps(func)
     34 def wrapper(*args, **kwargs):
---> 35     return func(*args, **kwargs)

File ~/.conda/envs/ofir_env/lib/python3.8/site-packages/captum/attr/_core/saliency.py:130, in Saliency.attribute(self, inputs, target, abs, additional_forward_args)
    126 gradient_mask = apply_gradient_requirements(inputs)
    128 # No need to format additional_forward_args here.
    129 # They are being formated in the `_run_forward` function in `common.py`
--> 130 gradients = self.gradient_func(
    131     self.forward_func, inputs, target, additional_forward_args
    132 )
    133 if abs:
    134     attributions = tuple(torch.abs(gradient) for gradient in gradients)

File ~/.conda/envs/ofir_env/lib/python3.8/site-packages/captum/_utils/gradient.py:119, in compute_gradients(forward_fn, inputs, target_ind, additional_forward_args)
    113     assert outputs[0].numel() == 1, (
    114         "Target not provided when necessary, cannot"
    115         " take gradient with respect to multiple outputs."
    116     )
    117     # torch.unbind(forward_out) is a list of scalar tensor tuples and
    118     # contains batch_size * #steps elements
--> 119     grads = torch.autograd.grad(torch.unbind(outputs), inputs)
    120 return grads

File ~/.conda/envs/ofir_env/lib/python3.8/site-packages/torch/autograd/__init__.py:223, in grad(outputs, inputs, grad_outputs, retain_graph, create_graph, only_inputs, allow_unused)
    220 if retain_graph is None:
    221     retain_graph = create_graph
--> 223 return Variable._execution_engine.run_backward(
    224     outputs, grad_outputs_, retain_graph, create_graph,
    225     inputs, allow_unused, accumulate_grad=False)

RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([1, 64, 32, 32], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(64, 64, kernel_size=[3, 3], padding=[1, 1], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams 
    data_type = CUDNN_DATA_FLOAT
    padding = [1, 1, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x7f176005cad0
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 1, 64, 32, 32, 
    strideA = 65536, 1024, 32, 1, 
output: TensorDescriptor 0x7f176005cb80
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 1, 64, 32, 32, 
    strideA = 65536, 1024, 32, 1, 
weight: FilterDescriptor 0x7f1760000d40
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 64, 64, 3, 3, 
Pointer addresses: 
    input: 0x7f17a3f9c400
    output: 0x7f17969bee00
    weight: 0x7f17aaf00000
Additional pointer addresses: 
    grad_output: 0x7f17969bee00
    grad_weight: 0x7f17aaf00000
Backward filter algorithm: 5`

**Comment by annahedstroem** [comment]
Hi, thanks a lot. I've fixed the problem in the notebook now, committing changes as we speak ...

These were changes necessary:


 ```
# Explain model (on a few test samples) and measure sensitivies.
sensitivities[epoch] = sensitivities[epoch] = quantus.MaxSensitivity(**{"nr_samples": 10,
                                                                        "perturb_radius": 0.2,
                                                                        "norm_numerator": quantus.fro_norm,
                                                                        "norm_denominator": quantus.fro_norm,
                                                                        "explain_func": quantus.explain,
                                                                        "perturb_func": quantus.uniform_noise,
                                                                        "similarity_func": quantus.difference,
                                                                    })(model=model, 
                                                                    x_batch=x_batch.cpu().numpy(),
                                                                    y_batch=y_batch.cpu().numpy(),
                                                                    a_batch=None,
                                                                    **{"method": "Saliency", "device": device, "explain_func": quantus.explain}) ```
