### ISSUE TITLE
Add support for TF saved model / TF hub models

### ISSUE THREAD

**Issue by aaarrti** [understandable-machine-intelligence-lab/Quantus#137]
In TF it's common practise to use `tf.saved_model` format, for (de)serialising trained models. This format has however a bit 
other APIs than `tf.keras.Model`. It would be great to have Quantus support it.

Also whilst on it, imo it would make sense to also support https://tfhub.dev/, since this is also a popular format for sharing pre-trained TF models

![image](https://user-images.githubusercontent.com/44274784/184477424-bc28a483-6878-46e1-92c8-e7887ade3010.png)

**Comment by annahedstroem** [comment]
Sounds good. Let's sync on it :)

**Comment by aaarrti** [comment]
So, as per official documentation:

A SavedModel contains a complete TensorFlow program, including trained parameters (i.e, [tf.Variable]
(https://www.tensorflow.org/api_docs/python/tf/Variable)s) and computation. 
It does not require the original model building code to run, which makes it 
useful for sharing or deploying with [TFLite](https://tensorflow.org/lite), [TensorFlow.js](https://js.tensorflow.org/), 
[TensorFlow Serving](https://www.tensorflow.org/tfx/serving/tutorials/Serving_REST_simple), or [TensorFlow Hub](https://tensorflow.org/hub).

Which basically means we get `Callable`, we can use to run inference, however no access to internals: like layers, activations and we can't modify it's behaviour. Because only (compiled) computational graph is saved.

I'd say it makes no sense to support this. So I'l close the issue, or rather cancel the feature request
