### ISSUE TITLE
Find out how to render text heat maps in GitHub preview

### ISSUE THREAD

**Issue by aaarrti** [understandable-machine-intelligence-lab/Quantus#173]
From top to down the views generated by:
- PyCharm
- Colab
- JupyterLab
- GitHub preview

![image](https://user-images.githubusercontent.com/44274784/195724278-57cc842f-40d3-4e2f-81d3-1646bef8535f.png)
![image](https://user-images.githubusercontent.com/44274784/195724312-657a20e1-31d4-409c-a690-e939a40db67f.png)
![image](https://user-images.githubusercontent.com/44274784/195724442-e5b89262-47b2-45fc-bcd0-021baa2fe5a1.png)
![image](https://user-images.githubusercontent.com/44274784/195724510-52b0c35e-a858-49e5-b688-24cbf8e17d0b.png)

Ideally, we want them all to be rendered in the same view. I think this could be caused by GitHub preview treating Jupyter notebook as HTML itself and applying some of GitHub's CSS onto it. It would be event better if we find a library to **reliably** render heat maps for us

**Comment by aaarrti** [comment]
so, here is the answer https://stackoverflow.com/questions/74046734/plot-text-saliency-map-in-jupyter-notebook

**Comment by annahedstroem** [comment]
Fixed by @aaarrti !
