### ISSUE TITLE
Extend functionality of quantus.evaluate to be more general

### ISSUE THREAD

**Issue by leanderweber** [understandable-machine-intelligence-lab/Quantus#199]
### Description of the problem
- The current `quantus.evaluate()` function expects the `xai_methods` argument to have a structure which does not fit all possible explanation frameworks (even those wrapped by quantus, e.g., `zennit`). Specifically, it expects each explanation method to be defined either via a string or a callable. This is in contrast to the general implementation of quantus.explain, which basically just expects the explanation method to be simply defined by the `**kwargs`, and is therefore much more general.

- Similarly, some form of iteration over the `metric_call_kwargs` should also be supported. Again, this would fit better with the relatively recent API changes of metrics in quantus. For instance, a user my want to evaluate with `softmax=True` as well as `softmax=False`, or different `model_predict_kwargs`. In the future, more important arguments could also be added to the `__call__` method of metrics, so iteration over those might be desirable.

### Description of a solution
- [x] Make `xai_methods` a Union[Dict[str, Callable], Dict[str, Dict]], where the second option would be of the form `{method: explain_func_kwargs}`. 
- [x] Remove the then redundant `explain_func_kwargs` argument from quantus.evaluate. 
- [x] Add a third loop iterating over different `call_kwargs`
- [x] Make `call_kwargs` of type Dict[str, Dict]
- [x] Update Docs :)

### Minimum acceptance criteria
- This is not a very significant change, but it changes the API of `quantus.evaluate()`, so it needs to be communicated properly.
- Some consideration should be given to usability also. Does it make sense to keep some form of accessing xai_methods via string (i.e., List[str]) to simply make evaluation more comfortable?
- Pls review @annahedstroem

**Comment by annahedstroem** [comment]
Looks great! Added you as a reviewer @leanderweber 

See: https://github.com/understandable-machine-intelligence-lab/Quantus/pull/214

**Comment by annahedstroem** [comment]
Already completed.
