### ISSUE TITLE
Minor misleading error message in Robustness metrics

### ISSUE THREAD

**Issue by leanderweber** [understandable-machine-intelligence-lab/Quantus#201]
### Description
When failing to provide an explain_func for the robustness metrics, an error message states:
```AssertionError: Make sure 'explain_func' is a Callable that takes model, x_batch, y_batch and **kwargs as arguments.```

However, the correct signature for explain_func is `model, inputs, targets and **kwargs`.

This is important as these are internally used by their name, not only by position.

### Steps to reproduce the behavior
See description. This is very minor.

### Minimum acceptance criteria
- Change two words in the error message :)
- @annahedstroem

**Comment by annahedstroem** [comment]
Already completed.
