### ISSUE TITLE
docstring for RelevanceMassAccuracy metric does not match implementation

### ISSUE THREAD

**Issue by leanderweber** [understandable-machine-intelligence-lab/Quantus#213]
### Description
The docstring for the RelevanceMassAccuracy metric states "The Relevance Mass Accuracy computes the ratio of positive attributions inside the bounding box to the sum of overall positive attributions". However, both in the implementation within quantus, as well as in the corresponding paper (https://www.sciencedirect.com/science/article/pii/S1566253521002335), both positive and negative attributions are considered.

### Minimum acceptance criteria
- [x] Update the docstring to reflect the implementation of the metric.
- pls review @annahedstroem

**Comment by annahedstroem** [comment]
Done in commit https://github.com/understandable-machine-intelligence-lab/Quantus/pull/256/commits/efe19d8bbdfdd1c55b71cfafd78043064d8d8695
