### ISSUE TITLE
Possible error in the application of aggregate_func in the 'Metric' class found in the 'base.py' script, especialy while using numpy methods.

### ISSUE THREAD

**Issue by Shreyas-Gururaj** [understandable-machine-intelligence-lab/Quantus#220]
![Screenshot from 2023-01-10 01-02-41](https://user-images.githubusercontent.com/75955459/211433060-1c7fc51a-ad5a-4cc6-b953-bc133a661ae3.png)

Please confirm whether the mean should only be aggregated over the axis=0 direction, i.e along the number of steps (Fraction of pixels flipped)

Essentially the line 235 would be replaced by line 239 in the attached reference picture.

Thanks,
Shreyas Gururaj.

**Comment by dilyabareeva** [comment]
@Shreyas-Gururaj Thanks for your feedback! Could you provide more detail about the metric you were trying to use, and maybe a code snippet that would help us to recreate the error? That would be very helpful.

**Comment by dilyabareeva** [comment]
@Shreyas-Gururaj Quantus provides flexibility in terms of aggregate function choice. For your case, I would suggest passing `aggregate_func=lambda x: numpy.mean(x, axis=0)` to the metric. Changing the base class to include axis=0 as you suggest might not make sense for all the metrics. Hope this helps.

**Comment by Shreyas-Gururaj** [comment]
@dilyabareeva Hi, Thanks for the update. Yes, that might break other running codes. I would make the necessary changes.
