### ISSUE TITLE
plot() missing 1 required positional argument: 'plot_func'

### ISSUE THREAD

**Issue by KumarAshitabh** [understandable-machine-intelligence-lab/Quantus#242]
Getting error here 
# Plot example!
pixel_flipping.plot(y_batch=y_batch, scores=scores)

message:
TypeError: plot() missing 1 required positional argument: 'plot_func'

**Comment by annahedstroem** [comment]
Thanks a lot for this! Is this run from a notebook, which one?

Will investigate.

**Comment by binh-nguyen49-jh** [comment]
It seems plot_func is a required parameter of this function, could I pass plot_func=None into this function? 
<img width="967" alt="image" src="https://user-images.githubusercontent.com/101536791/234200097-d5fe1399-17f1-45a5-b4a6-b5680b17856e.png">

**Comment by annahedstroem** [comment]
Awesome, I'll update that is the source code.
