### ISSUE TITLE
Some minor mistakes in the documentation

### ISSUE THREAD

**Issue by EricKolibacz** [understandable-machine-intelligence-lab/Quantus#268]
### Description
Thanks for the great project foremost! I went through the ReadMe of the project to use it for an XAI method I am working on. While working my way through, I encountered some small spelling mistakes and some errors in the provided example code. Nothing groundbreaking, but I guess others who will be using the ReadMe as a first guidance might encounter the same problems. 

I fixed the things I found in a local branch. Easiest would be if I could receive sufficient rights to push the branch and create corresponding pull request. Otherwise, I can post my changes here to the issue.

### ~~Steps to reproduce the behavior~~ Some examples
[here](https://github.com/understandable-machine-intelligence-lab/Quantus/blob/main/README.md?plain=1#L238):
 ```python
torchvision.datasets.MNIST(root='./sample_data', download=True, transforms=transforms.Compose([transforms.ToTensor()]))
```
 raises an error because the parameter `transforms` does not exist. Probably `transform`.

or

[here](https://github.com/understandable-machine-intelligence-lab/Quantus/blob/main/README.md?plain=1#L269): 2nd variable probably should be `a_batch_integrated`
```python
a_batch_saliency = load("path/to/precomputed/saliency/explanations")
a_batch_saliency = load("path/to/precomputed/intgrad/explanations")
```
and some minor ones

### Minimum acceptance criteria
- the small mistakes fixed

**Comment by aaarrti** [comment]
Hi @EricKolibacz, 
thanks for pointing out the issue! The fix should be live very soon. 
For the future, if you want to contribute on a similar issue, please create a fork of the repository, then you would be allowed to open a pull request (from your fork into the main repository)!

**Comment by EricKolibacz** [comment]
Hi @aaarrti 

Alright, next time I will do so :+1: The other minor mistakes I found in the documentation:

[This important path](https://github.com/understandable-machine-intelligence-lab/Quantus/blob/main/README.md?plain=1#L320) did not work for me. I fixed it by modifying it to this
```python
metric = quantus.MaxSensitivity(nr_samples=10,
                                lower_bound=0.2,
                                norm_numerator=quantus.functions.norm_func.fro_norm,
                                norm_denominator=quantus.functions.norm_func.fro_norm,
                                perturb_func=quantus.uniform_noise,
                                similarity_func=quantus.difference)
```

A missing `:` at [the end of the function's output type hint](https://github.com/understandable-machine-intelligence-lab/Quantus/blob/main/README.md?plain=1#L362).

And newer `torch` version does not support [this syntax](https://github.com/understandable-machine-intelligence-lab/Quantus/blob/main/README.md?plain=1#L242) anymore, so:
```python
x_batch, y_batch = iter(test_loader).next() # next(iter(test_loader)) for newer versions of torch
```
