### ISSUE TITLE
Getting started tutorial needs to specify explain_fun for MaxSensitivity metric

### ISSUE THREAD

**Issue by smachar** [understandable-machine-intelligence-lab/Quantus#276]
### Description
The getting started tutorial doesn't run as expected when passing pre-calculated explanations/attribution to the MaxSensitivity metric.

### Error's source code
```
metric = quantus.MaxSensitivity(nr_samples=10,
  lower_bound=0.2,
  norm_numerator=quantus.fro_norm,
  norm_denominator=quantus.fro_norm,
  perturb_func=quantus.uniform_noise,
  similarity_func=quantus.difference)

scores = metric(
    model=model,
    x_batch=x_batch,
    y_batch=y_batch,
    a_batch=a_batch_saliency,
    device=device
)
```
When calculating the scores the MaxSensitivity gives the following error:
```
AssertionError: Make sure 'explain_func' is a Callable that takes model, inputs, targets and **kwargs as arguments.
```
Which is expected as the metric requires the ```explain_fun``` in order to evaluate the perturbed inputs.

### Minimum acceptance criteria
- Clearly specify in the tutorial what arguments are required by the metric.

**Comment by annahedstroem** [comment]
Hi @smachar can you please link which tutorial you are referring to?

Cause the basic getting started tutorial (https://github.com/understandable-machine-intelligence-lab/Quantus/blob/main/tutorials/Tutorial_Getting_Started.ipynb) looks different from the code snippet you've created.


![image](https://github.com/understandable-machine-intelligence-lab/Quantus/assets/29717021/f9e7554e-893f-4b0d-a34c-a53ae38cdab1)

**Comment by smachar** [comment]
Here [https://github.com/understandable-machine-intelligence-lab/Quantus]( https://github.com/understandable-machine-intelligence-lab/Quantus ), in the main page **Step 3. Evaluate with Quantus**
