### ISSUE TITLE
Wrong implementation in max_sensitivity.py

### ISSUE THREAD

**Issue by Sangyu-Han** [understandable-machine-intelligence-lab/Quantus#288]
### Description
- Insert a clear and concise description of what the bug is.
In max_sensitivity.py line 386, the denominator use a=x_batch[instance_id]. but It seems that it should be a_batch[instance_id], as the  original code https://github.com/chihkuanyeh/saliency_evaluation/blob/master/infid_sen_utils.py, line 308 use normlization of explanation.

### Steps to reproduce the behavior
- Insert a description of the steps one needs to take to be able to reproduce the issue.
  - Step 1
  - Step 2
  - Step 3
- Insert a clear and concise description of what you expected to happen.
- If applicable, add screenshots to help explain your problem.
- Add any other context about the problem here. For example, set-up to run example.

### Minimum acceptance criteria
- Specify what is necessary for the issue to be closed.
- @mentions of the person that is apt to review these changes e.g., @annahedstroem

**Comment by annahedstroem** [comment]
Fixed in PR https://github.com/understandable-machine-intelligence-lab/Quantus/pull/289.
