### ISSUE TITLE
toml missing

### ISSUE THREAD

**Issue by jdegange** [understandable-machine-intelligence-lab/Quantus#292]
### Description
- I now can't install in colab. Stack trace:
~~~bash
[/usr/local/lib/python3.10/dist-packages/quantus/__init__.py](https://localhost:8080/#) in <module>
      7 # Set the correct version.
      8 import toml
----> 9 package = toml.load("pyproject.toml")
     10 __version__ = package["project"]["version"]
     11 

[/usr/local/lib/python3.10/dist-packages/toml/decoder.py](https://localhost:8080/#) in load(f, _dict, decoder)
    131 
    132     if _ispath(f):
--> 133         with io.open(_getpath(f), encoding='utf-8') as ffile:
    134             return loads(ffile.read(), _dict, decoder)
    135     elif isinstance(f, list):

FileNotFoundError: [Errno 2] No such file or directory: 'pyproject.toml'
~~~

### Steps to reproduce the behavior
- Insert a description of the steps one needs to take to be able to reproduce the issue.
  - Step 1 Go to Colab
  - Step 2 Install from wheel or from git directly
  - Step 3 import quantus

### Minimum acceptance criteria
-successful import

**Comment by annahedstroem** [comment]
Thanks for highlighting. Fixed in https://github.com/understandable-machine-intelligence-lab/Quantus/releases/tag/v0.4.3.
