### ISSUE TITLE
Infer_channel_first called even if channel_first is set

### ISSUE THREAD

**Issue by sergedurand** [understandable-machine-intelligence-lab/Quantus#304]
### Description
infer_channel_first is always called, even if channel_first has been specified.

### Steps to reproduce the behavior
Consider a model with a number of channels greater than H and W, infer_channel_first will fail and suggest
to set manually channel_first. But even if set it will fail and raise the error.
```python
import quantus
import torch
from torch import nn

model = nn.Sequential(
    nn.Conv2d(in_channels=156, out_channels=16, kernel_size=(3, 3), stride=1),
    nn.ReLU(),
    nn.Flatten(),
)
x = torch.randn(1, 156, 32, 32)
# make a classifier out of the model
in_dim = model(x).shape[1]
classifier = nn.Sequential(model, nn.Linear(in_dim, 10))
target = torch.tensor([0])
```
Then 
```python
attr = quantus.explain(
    model=classifier,
    inputs=x,
    targets=target,
    method="IntegratedGradients",
)
```
Raises 
```python
ValueError: Ambiguous input shape. Cannot infer channel-first/channel-last order. Try setting the `channel_first` argument
```
but
```python
attr = quantus.explain(
    model=classifier,
    inputs=x,
    targets=target,
    method="IntegratedGradients",
    channel_first=True,
)
```
raises the same error. 
The channel_first argument is present in kwargs but using kwargs.get will evaluate the default value so if it can't be inferred it cannot be overridden.

Proposed fix: 
replace as follows where needed (l. 480 of [explaination_func](https://github.com/understandable-machine-intelligence-lab/Quantus/blob/main/quantus/functions/explanation_func.py) for instance)
```python
    # channel_first = kwargs.get("channel_first", infer_channel_first(inputs)) 
    chanel_first = kwargs["channel_first"] if "channel_first" in kwargs else infer_channel_first(inputs)
``` 

### Minimum acceptance criteria
- Get the channel_first value if present in kwargs without call to infer_channel_first.
- @annahedstroem

Related note: 
not as problematic but in the use 
```python
kwargs.get("baseline", torch.zeros_like(inputs))
```
A tensor of zeros of the size of inputs will be created even if a baseline is provided.

**Comment by annahedstroem** [comment]
Thanks @sergedurand for highlighting this issue and providing a suggestion for a solution. 

See PR: https://github.com/understandable-machine-intelligence-lab/Quantus/pull/305.

**Comment by annahedstroem** [comment]
The PR https://github.com/understandable-machine-intelligence-lab/Quantus/pull/305 is merged with main. Please check if the solution works for you @sergedurand so we can close the issue!

**Comment by sergedurand** [comment]
Yes it does, thanks for the fixes!
