### ISSUE TITLE
Wrong calculation of selectivity

### ISSUE THREAD

**Issue by JonasKlotz** [understandable-machine-intelligence-lab/Quantus#334]
### Description

If I am not mistaken, there is an error the calculation of the selectivity:
`results[patch_id] = y_pred_perturb`, however, AFAIK one should calculate the difference of the prediction on the original and perturbed input: `results[patch_id] = y_pred - y_pred_perturb`. 

This is also mentioned in the comment above:
`# Predict on perturbed input x and store the difference from predicting on unperturbed input. `

I am fairly new to the domain so if I'm wrong please excuse me. I already made a fix and have created a PR.
@annahedstroem

**Comment by annahedstroem** [comment]
Hi, thanks so much for your suggestion.

According to Figure 8 and the description in Section 7.2 in the original paper https://arxiv.org/pdf/1706.07979.pdf, I do however believe that the current implementation is correct.

Please share your source so we can compare!

(If you want, you can also add this functionality by creating a boolean flag like "compute_prediction_difference" (or with a better name) so to make your implementation available. Please then add 1-3 pytests to test it).

**Comment by JonasKlotz** [comment]
Hey Anna, thanks for the reply.

I've reread the paper and you're right. Sorry, I missed that.

It is not a different implementation, I think I was just confused by the comment
 [ # Predict on perturbed input x and store the difference from predicting on unperturbed input.](https://github.com/understandable-machine-intelligence-lab/Quantus/blob/47a41b15be43a164c6f42716aa9014a7dde90c99/quantus/metrics/faithfulness/selectivity.py#L363C12-L363C106) 
 and the calculation of y_pred in
[y_pred = float(model.predict(x_input)[:, y])](https://github.com/understandable-machine-intelligence-lab/Quantus/blob/47a41b15be43a164c6f42716aa9014a7dde90c99/quantus/metrics/faithfulness/selectivity.py#L298C1-L298C53),
Which is not necessary then, right?

**Comment by annahedstroem** [comment]
ah, good that you noticed it! I'll update the comment.
