### ISSUE TITLE
Region Perturbation plotting cannot deal with certain multi-dimensional data (image no. > 1, explain_func no. == 1) 

### ISSUE THREAD

**Issue by tlabarta** [understandable-machine-intelligence-lab/Quantus#352]
### Description
The Region Perturbation plotting function throws a shape mismatch error, when trying to plot e.g. results obtained for a batch of three images for one explain function. In this case, region perturb will return a list of np.shape(batch_size, perturbation_steps). For the plotting to work, we need the perturbation steps as x_value and the results as y_value. However as is, the x_value is determined by len(results), which will return the batch_size instead of the perturbation steps.

I will raise a pull request to fix this issue right after opening this issue.

### Steps to reproduce the behavior
  - Calculate Region Perturbation results for len(x_batch) > 1 for one explainer, using quantus.RegionPerturbation
  - Try to plot the results using quantus.RegionPerturbation.plot(results=results)

<img width="875" alt="image" src="https://github.com/user-attachments/assets/ec4997bb-4a86-4c1f-ac3f-3a5854b3757e">

### Minimum acceptance criteria
- allow for plotting of one-dimensional and multi-dimensional results lists.
- briefly discussed with @annahedstroem

**Comment by annahedstroem** [comment]
Fixed in PR: https://github.com/understandable-machine-intelligence-lab/Quantus/commit/bbe77038ad4b6111336ba6a3b62e27582c2d4002

Thanks @tlabarta
