### ISSUE TITLE
Application on A Customized Method 

### ISSUE THREAD

**Issue by soumiadjellikh** [understandable-machine-intelligence-lab/Quantus#355]
- If I want to apply it in a customized method
- I want the pseudo code or the general scheme for this purpose

- Would You Please guide me @annahedstroem

**Comment by annahedstroem** [comment]
Hi @soumiadjellikh what do you mean by a customised method? Can you provide more details so I can help?

**Comment by soumiadjellikh** [comment]
hello @annahedstroem , I mean a newly proposed XAI method that I want to evaluate and compare with other XAI methods using Quantus

**Comment by annahedstroem** [comment]
Please check the documentation — we have examples for that use case, i.e., to create your own Callable. 

See e.g., https://quantus.readthedocs.io/en/latest/getting_started/getting_started_example.html.

Thanks"
