### ISSUE TITLE
Allow for more variable shapes of attributions and inputs

### ISSUE THREAD

**Issue by leanderweber** [understandable-machine-intelligence-lab/Quantus#51]
Shapes of accepted inputs/attributions in metrics are hard-coded and very restrictve to specific data domains currently.

Mainly opening this issue as a reminder to extend functionality to other, non-image domains, and allow for shape flexibility.
For instance, in some applications, channel-wise attributions may carry meaningful information.

Of course, this may only be feasible for a subset of quantification metrics.

**Comment by Wickstrom** [comment]
I have come quite far, it should be ready in the coming days.

**Comment by Wickstrom** [comment]
It turns out, that allowing for flexible image size was a bigger job than expected ping @leanderweber @annahedstroem. I will incrementally adapt the metrics individually to allow for flexible image size in the "flexible-imgsize" branch. But it will take some time before all of them are ready.

**Comment by sebastian-lapuschkin** [comment]
it might be worthwhile to already consider arbitrarily shaped tensor data, to eg. also support (multi channel) time series data

**Comment by annahedstroem** [comment]
this is an effort ongoing, see 2 separate PRs:
1)  https://github.com/understandable-machine-intelligence-lab/Quantus/pull/73
2) https://github.com/understandable-machine-intelligence-lab/Quantus/pull/74

**Comment by dkrako** [comment]
Support for variable shapes of inputs was added by [1d and non squared 2d input shapes #74](https://github.com/understandable-machine-intelligence-lab/Quantus/pull/74)

This enhancement should actually support any `numpy.ndarray` shapes, as long as there's a batch dimension (axis=0), the channel is at the beginning (axis=1) or at the end (axis=-1) and `channel_first` is passed explicitly. Inference of channel order (channel first or last) supports only unambiguous 1d and 2d inputs.

Unfortunately 1d-support is NOT implemented for the following functions/metrics:
- `baseline_replacement_by_blur`: uses `conv2D_numpy`, `scipy.signal.convolve` could solve the issue
- `rotation, translation_x_direction`, `translation_y_direction`: `cv2` expects images as input
- `get_superpixels`: `skimage` also expects 2d input
- `IterativeRemovalOfFeatures` therefore won't work for 1d yet.

**Comment by annahedstroem** [comment]
Ping @leanderweber,

given @dkrako concluding comment, would you agree that we can now close this issue?

Let me know your thoughts - if there is anything else you believe Quantus should support related to this issue.
