### ISSUE TITLE
Potentially dead code

### ISSUE THREAD

**Issue by dilyabareeva** [understandable-machine-intelligence-lab/Quantus#52]
Hi Anna, please check this potentially dead/erroneous code. I think me might need to remove it.

https://github.com/understandable-machine-intelligence-lab/Quantus/blob/4dda6f53b8bc0356cb9659c32329b9d68e4b2f3a/quantus/metrics/robustness_metrics.py#L759-L775

https://github.com/understandable-machine-intelligence-lab/Quantus/blob/4dda6f53b8bc0356cb9659c32329b9d68e4b2f3a/quantus/metrics/randomisation_metrics.py#L318-L329

**Comment by annahedstroem** [comment]
Thanks Dilya! 

> Quantus/quantus/metrics/randomisation_metrics.py
is removed, will be included in upcoming commit to main

> Quantus/quantus/metrics/robustness_metrics.py
I think can be useful to keep, included an example to tutorial.
