### ISSUE TITLE
Rotten link in README/Tutorials

### ISSUE THREAD

**Issue by heytitle** [understandable-machine-intelligence-lab/Quantus#53]
Hi,

It seems that the link of this tutorial is rotten: https://github.com/understandable-machine-intelligence-lab/Quantus/blob/main/README.md?plain=1#L226.

The link is
```
https://.../quantus/blob/main/tutorials/tutorial_[sensitivity]_parameterisation.ipynb
```
and the tutorial actually locates at
 
```
https://.../Quantus/blob/main/tutorials/tutorial_[sensivitivty]_parameterisation.ipynb
``` 

Noting that I added the brackets to emphasize the part that the two links differ and causes 404.  

Given that it looks like a small typo in the filename, we can fix it there and the link in README.md the same.

**Comment by annahedstroem** [comment]
Thanks for noticing this! Very appreciated. It is fixed now and will be incorporated in the upcoming commit :)
