### ISSUE TITLE
Update setup.py for including zennit library

### ISSUE THREAD

**Issue by leanderweber** [understandable-machine-intelligence-lab/Quantus#55]
For pytorch case: Check if zennit is installed. If it is, neither captum nor zennit need to be installed

**Comment by annahedstroem** [comment]
fixed in https://github.com/understandable-machine-intelligence-lab/Quantus/pulls

**Comment by leanderweber** [comment]
No zennit installation option in the setup.py yet right?

**Comment by annahedstroem** [comment]
@leanderweber ping, see suggestion in https://github.com/understandable-machine-intelligence-lab/Quantus/pull/114.

**Comment by annahedstroem** [comment]
Issue fixed here https://github.com/understandable-machine-intelligence-lab/Quantus/pull/114#pullrequestreview-943850575.
