### ISSUE TITLE
Suggestion on Readability of README 

### ISSUE THREAD

**Issue by heytitle** [understandable-machine-intelligence-lab/Quantus#58]
While going through `README`, I have noticed that the section that describes metrics implemented is very long. Perhaps, we could use the `<details></details>` to hide the content.

More precisely, we could do it like:

*(below is snippet from `README` with the suggested approach)*

...
The library contains implementations of the following evaluation metrics:

<details>
<summary><b>Faithfulness:</b> ...</summary>

- Paper 1
- Paper 2
</details> 

<details>
<summary><b>Robustness:</b> ...</summary>

- Paper 1
- Paper 2
</details>

**Comment by annahedstroem** [comment]
Great suggestion - change just committed.
