### ISSUE TITLE
Small typo in Tutorial

### ISSUE THREAD

**Issue by heytitle** [understandable-machine-intelligence-lab/Quantus#66]
Hi,

I have found a small typo in https://github.com/understandable-machine-intelligence-lab/Quantus/blob/main/tutorials/tutorial_basic_example_all_metrics.ipynb.

![image](https://user-images.githubusercontent.com/1214890/155402363-2d529239-ecb7-46a9-b912-8ffc6fd37fed.png)

**Comment by annahedstroem** [comment]
Thanks a lot - fixed.
