### ISSUE TITLE
Ability to Specify Seed for RandomLogit

### ISSUE THREAD

**Issue by heytitle** [understandable-machine-intelligence-lab/Quantus#67]
The current implementation of `RandomLogit` uses `random` to select target labels, but it doesn't  seem to provide ways to control the random process.

I just wonder whether it would be a good idea to provide another argument (e.g., `seed`) for that. 

The same idea might be applicable for `ModelParameterRandomisation`.

**Comment by sebastian-lapuschkin** [comment]
it might make sense to globally set a random seed rather than per function call?

**Comment by annahedstroem** [comment]
Sounds like a good idea @heytitle! I will include that in upcoming commits :-)

**Comment by annahedstroem** [comment]
Fixed
