### ISSUE TITLE
Tutorial on how to use tensorflow models

### ISSUE THREAD

**Issue by annahedstroem** [understandable-machine-intelligence-lab/Quantus#71]
Would be great with a tutorial that shows:

- how to use tensorflow models

Maybe call the tutorial something like: tutorial-evaluate-with-tensorflow-model

**Comment by sebastianlutter** [comment]
+1

**Comment by annahedstroem** [comment]
Fixed in this PR https://github.com/understandable-machine-intelligence-lab/Quantus/pull/81 :) 

@sebastianlutter
