### ISSUE TITLE
PixelFlipping metric only flips first color channel

### ISSUE THREAD

**Issue by frederikpahde** [understandable-machine-intelligence-lab/Quantus#75]
Hi,
I think I found a bug in the PixelFlipping implementation. Using the perturbation baseline "black", I noticed that only the first color channel (red) is set to 0. I would have expected all channels to be set to 0.
I initialized the metric as demonstrated in the tutorials with the following code:
```
quantus.PixelFlipping(**{
      "features_in_step": 28, 
      "perturb_baseline": "black", 
      "perturb_func": quantus.baseline_replacement_by_indices
})
```

Plotting the perturbed images for a couple of iterations leads to the following images, where **top** is produced by the current implementation and **bottom** is what I expected (perturbing all color channels):
<img src="https://user-images.githubusercontent.com/5980264/156534521-0336cdfc-2bf3-41b3-b896-3d7b35d3c249.png"  width="70%">

I think the problem is caused [here](https://github.com/understandable-machine-intelligence-lab/Quantus/blob/7f96cc6ca28dc0fdd10ee74d045a2890bdb17d8d/quantus/metrics/faithfulness_metrics.py#L1114), because `x_perturbed` has dimension _num_col_channels_ x _img_size_ x _img_size_ and `a_ix` only has dimension _img_size_ x _img_size_. 

I solved this locally with a quick workaround (which produced the **bottom** images in the figure above):
```
num_channels = 3
a_ix = np.concatenate([a_ix + (ch * len(a)) for ch in range(num_channels)])
```
However, since the perturbation is performed on normalized images, the normalized value for 0 can differ by color channel. This is not addressed in this quick fix.

**Comment by annahedstroem** [comment]
Thanks @frederikpahde for making me aware of this issue and for documenting it very well. You can expect the fixes to be incorporated in next commit to main :-)

**Comment by annahedstroem** [comment]
Fixed in the following commit: https://github.com/understandable-machine-intelligence-lab/Quantus/commit/b0d6554f40556ce12ede0cb5abceba2114f83ffc
