### ISSUE TITLE
Unify Requirements of Perturb Functions and their Usage in the Metrics

### ISSUE THREAD

**Issue by leanderweber** [understandable-machine-intelligence-lab/Quantus#77]
The currently implemented perturb functions have different requirements, e.g., in terms of expected input shape, and are thus not really interchangable for all metrics. Requirements should either be unified for perturb functions, or at least an informative error message should be thrown in the metrics if an inapplicable perturb function is used.

**Comment by dkrako** [comment]
I think the most clean way of doing this would be to create some abstract classes or interfaces with abstract methods which specify the expected inputs, e.g. `IndexPerturbatorInterface` or `PatchPerturbatorInterface`. The calling metric then would just need to check if the passed perturbator object inherits from the expected type of perturbator.
This would also have the benefit of instantiating the perturbator object beforehand with any arguments wanted without unnecessarily dragging these arguments through the `Metric` implementations.
