### ISSUE TITLE
torch-xai: zennit

### ISSUE THREAD

**Issue by sebastian-lapuschkin** [understandable-machine-intelligence-lab/Quantus#8]
let's use zennit for computing xai for stuff captum can not deliver, ie in https://github.com/xai-quantification-toolbox/xai-quantification-toolbox/blob/main/nbs/nb_test_measures.ipynb

**Comment by annahedstroem** [comment]
zennit supported in https://github.com/understandable-machine-intelligence-lab/Quantus/pull/59
